services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.3.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.config:/config
      - ./custom_components:/config/custom_components:ro
    environment:
      - TZ=Europe/Rome
    restart: unless-stopped
    ports:
      - '8123:8123'
